apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-keda-cluster
spec:
  replicas: 1
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1500
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  service:
    type: ClusterIP
